<div class="field">
    <label for="shipping:altura" class="required">
        <?php echo $this->__('Altura') ?>
    </label>
    <div class="input-box">
        <input type="text" name="shipping[altura]" id="shipping:altura" value="<?php echo $this->escapeHtml($this->getAddress()->getAltura()) ?>" title="<?php echo $this->__('Altura') ?>" class="input-text required-entry validate-number" />
    </div>
</div>
<div class="field">
    <label for="billing:piso" class="">
        <?php echo $this->__('Piso') ?>
    </label>
    <div class="input-box">
        <input type="text" name="billing[piso]" id="billing:piso" value="<?php echo $this->escapeHtml($this->getAddress()->getPiso()) ?>" title="<?php echo $this->__('Piso') ?>" class="input-text validate-number" />
    </div>
</div>
<div class="field">
    <label for="billing:departamento" class="">
        <?php echo $this->__('Departamento') ?>
    </label>
    <div class="input-box">
        <input type="text" name="billing[departamento]" id="billing:departamento" value="<?php echo $this->escapeHtml($this->getAddress()->getDepartamento()) ?>" title="<?php echo $this->__('Departamento') ?>" class="input-text" />
    </div>
</div>
<div class="field">
    <label for="shipping:observaciones">
        <?php echo $this->__('Observaciones') ?>
    </label>
    <div class="input-box">
        <input type="text" name="shipping[observaciones]" id="shipping:observaciones" value="<?php echo $this->escapeHtml($this->getAddress()->getObservaciones()) ?>" title="<?php echo $this->__('Observaciones') ?>" class="input-text" />
    </div>
</div>